version: '3.8'
services:
  client:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./client:/usr/share/nginx/digitalex-html        
  
  mongodb:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
